name: AdminWatchdog
version: "1.3"
main: com.github.tejaslamba2006.adminwatchdog.AdminWatchdog
api-version: "1.21"

commands:
  adminwatchdog:
    description: "AdminWatchdog plugin commands"
    usage: "/<command> <version|v|ver|reload|rl|update|checkupdate>"
    aliases: [aw, awdog]

permissions:
  adminwatchdog.*:
    description: "All AdminWatchdog permissions"
    children:
      adminwatchdog.reload: true
      adminwatchdog.monitor: true
      adminwatchdog.update.check: true
      adminwatchdog.update.notify: true
    default: op

  adminwatchdog.reload:
    description: "Allows reloading plugin configuration"
    default: op

  adminwatchdog.monitor:
    description: "Permission for monitoring commands (configurable)"
    default: op

  adminwatchdog.update.check:
    description: "Allows manually checking for updates"
    default: op

  adminwatchdog.update.notify:
    description: "Receive update notifications when available"
    default: op

  adminwatchdog.bypass.*:
    description: "All bypass permissions"
    children:
      adminwatchdog.bypass.commands: true
      adminwatchdog.bypass.creative: true
      adminwatchdog.bypass.customresponses: true
      adminwatchdog.bypass.gamemode: true
    default: false

  adminwatchdog.bypass.commands:
    description: "Bypass command monitoring"
    default: false

  adminwatchdog.bypass.creative:
    description: "Bypass creative inventory monitoring"
    default: false

  adminwatchdog.bypass.customresponses:
    description: "Bypass custom response triggers"
    default: false

  adminwatchdog.bypass.gamemode:
    description: "Bypass gamemode change monitoring"
    default: false
