name: AdminWatchdog
version: "1.0"
main: com.github.tejaslamba2006.adminwatchdog.AdminWatchdog
api-version: "1.20"

commands:
  adminwatchdog:
    description: "AdminWatchdog plugin commands"
    usage: "/<command> <version|v|ver|reload|rl|update|checkupdate>"
    aliases: [aw, awdog]

permissions:
  adminwatchdog.*:
    description: "All AdminWatchdog permissions"
    children:
      adminwatchdog.reload: true
      adminwatchdog.monitor: true
      adminwatchdog.update.check: true
      adminwatchdog.update.notify: true
    default: op

  adminwatchdog.reload:
    description: "Allows reloading plugin configuration"
    default: op

  adminwatchdog.monitor:
    description: "Permission for monitoring commands (configurable)"
    default: op

  adminwatchdog.update.check:
    description: "Allows manually checking for updates"
    default: op

  adminwatchdog.update.notify:
    description: "Receive update notifications when available"
    default: op
